export const lastMonthExpenses = [
  {
    category: "service",
    dateTimestamp: "2023-02-21T10:30:00.000Z",
    transaction: true,
    description: "Monthly internet bill",
    amount: 50.0,
    paymentMethod: "Credit Card",
  },
  {
    category: "home",
    dateTimestamp: "2023-02-21T14:20:00.000Z",
    transaction: true,
    description: "Groceries from local store",
    amount: 75.2,
    paymentMethod: "Debit Card",
  },
  {
    category: "games",
    dateTimestamp: "2023-02-20T18:45:00.000Z",
    transaction: true,
    description: "Purchase of new video game",
    amount: 59.99,
    paymentMethod: "PayPal",
  },
  {
    category: "papers",
    dateTimestamp: "2023-02-20T11:00:00.000Z",
    transaction: true,
    description: "Newspaper subscription for the month",
    amount: 15.0,
    paymentMethod: "Cash",
  },
  {
    category: "videos",
    dateTimestamp: "2023-02-19T22:15:00.000Z",
    transaction: true,
    description: "Rental of movie from streaming service",
    amount: 3.99,
    paymentMethod: "Credit Card",
  },
  {
    category: "security",
    dateTimestamp: "2023-02-19T14:50:00.000Z",
    transaction: true,
    description: "Renewal of antivirus software subscription",
    amount: 30.0,
    paymentMethod: "Debit Card",
  },
  {
    category: "gas",
    dateTimestamp: "2023-02-18T09:15:00.000Z",
    transaction: true,
    description: "Refueling of car",
    amount: 50.0,
    paymentMethod: "Credit Card",
  },
  {
    category: "travel",
    dateTimestamp: "2023-02-17T16:30:00.000Z",
    transaction: true,
    description: "Purchase of flight tickets for upcoming trip",
    amount: 300.0,
    paymentMethod: "Credit Card",
  },
  {
    category: "shops",
    dateTimestamp: "2023-02-16T13:00:00.000Z",
    transaction: true,
    description: "Clothing purchase from mall",
    amount: 85.0,
    paymentMethod: "Debit Card",
  },
  {
    category: "home",
    dateTimestamp: "2023-02-16T10:00:00.000Z",
    transaction: true,
    description: "Bathroom cleaning supplies",
    amount: 20.0,
    paymentMethod: "Cash",
  },
  {
    category: "service",
    dateTimestamp: "2023-02-15T14:45:00.000Z",
    transaction: true,
    description: "Oil change for car",
    amount: 40.0,
    paymentMethod: "Cash",
  },
];
